listen-address=127.0.0.1,10.7.21.145
bind-interfaces

no-resolv
server=8.8.8.8
server=1.1.1.1

local=/team1.test/
host-record=app.team1.test,10.7.19.92
host-record=api.team1.test,10.7.19.92

domain-needed
bogus-priv
log-queries
